---
ID: "652f7589-f0af-4a03-971a-649e72a2dd89"
Parent: "1c52f786-e7c5-4a90-8e51-8c35b485e2bc"
Template: "1c52f786-e7c5-4a90-8e51-8c35b485e2bc"
Path: /sitecore/templates/Project/Website/Page Types/Default/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{A8735DCF-603F-4437-B39C-4FEE2BCD56D9}">
        <r
          id="{93E9BC1B-DF22-4C5F-817D-2AD069BCC8FF}"
          ph="main"
          uid="{34BDE865-1D8C-429A-8E4C-1E9C9E7DFD56}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{1AFC13DE-7DA2-4385-A583-BDD720175ECE}"
              p:after="*[1=2]"
              s:ds="{29352663-1942-485D-87EA-EE17DF25B8E0}"
              s:id="{41C02A39-52E8-4B25-9FE2-7494B585DCD0}"
              s:par=""
              s:ph="hero"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221005T175754Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "96a68063-f6d9-4169-a558-25e51dc9b9a2"
    - ID: "a867c205-0cb1-41b5-92b0-bfb2886d704a"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221030T232148Z
